project_id = "flkeoylxvqgbilundqrr"

[functions.create-admin]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.google-oauth]
verify_jwt = false

[functions.create-post]
verify_jwt = false

[functions.blog-rss]
verify_jwt = false

[functions.blog-sitemap]
verify_jwt = false
